language: java
cache:
  directories:
  - $HOME/.m2/repository

sudo: required

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo service mysql-5.6 stop || sudo service mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install jsvc
  - sudo pip install MySQL-python

install: true

script:
  - ./connect.sh

after_script:
  - mvn clean
  - python test_exit.py
