language: java
cache:
  directories:
  - $HOME/.m2/repository

sudo: required

jdk:
  - oraclejdk8

env:
  - source=maxwell

services:
  - docker


before_install:
  - mvn -version
  - python --version
  - sudo apt-get install python
  - sudo pip install MySQL-python

install: true

script: 
  - echo $SOURCE